Tagg/server/Tagg.Admin/Models/TeacherViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Tagg.Admin.Models
{
    public class TeacherViewModel
    {
        public string Id { get; set; }
        [Display(Name = "First Name")]

        public string FirstName { get; set; }
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        public string Email { get; set; }
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
        public string Bio { get; set; }

        [Display(Name = "School")]
        public string SchoolId { get; set; }
        public SelectList SchoolList { get; set; }

        [Display(Name = "School")]
        public string SchoolName { get; set; }
    }
}

Tagg/server/Tagg.Admin/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using MongoDB.Bson;
using Tagg.Admin.Models;
using Tagg.Domain;
using Tagg.Services;
using Tagg.Domain.ApiModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using AutoMapper;

namespace Tagg.Admin.Controllers
{
    public class JobsController : Controller
    {
        private readonly IConfiguration _config;
        private TaggApiService _api;
        private IMapper _mapper;

        public JobsController(
            IConfiguration config,
            TaggApiService api,
            IMapper mapper)
        {
            _config = config;
            _api = api;
            _mapper = mapper;

        }

        public async Task<IActionResult> Index()
        {
            var jobs = await _api.Jobs.GetAll();
            return View(jobs);
        }

        public async Task<IActionResult> Teachers()
        {
            var teachers = await _api.Teachers.GetByStatus("Active");
            return View(new TeacherSelectModel(teachers));
        }

        [HttpPost]
        public IActionResult Teachers(TeacherSelectModel model)
        {
            return RedirectToAction("Create", new { id = model.TeacherId });
        }

        [HttpGet]
        public async Task<IActionResult> Create(string id)
        {
            throw new NotImplementedException();
            var job = await populateDefaultJob(id);
            var model = new JobCreateViewModel(job);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(JobCreateViewModel job)
        {
            if (ModelState.IsValid)
            {
                var dto = _mapper.Map<JobCreateDto>(job);
                dto.Status = JobStatus.Open;
                var createResult = await _api.Jobs.Create(dto);
                return RedirectToAction("Index");
            }
            return View(job);
        }

        

        private async Task<JobDetailsDto> populateDefaultJob(string teacherId)
        {
            var teacher = await _api.Teachers.GetById(teacherId);
            var schools = await _api.Teachers.GetTeacherSchools(teacherId);
            var school = schools.FirstOrDefault();

            TimeSpan startTime;
            TimeSpan endTime;
            if (school != null && TimeSpan.TryParse(school.StartTime, out startTime) && TimeSpan.TryParse(school.EndTime, out endTime))
            {
                // TODO : FIX THIS LATER
                var result = new JobDetailsDto(new School(), new Teacher(), new Job());
                return result;
            }
            return null;
        }
    }
}

Tagg/server/Tagg.Admin/Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Tagg.Admin.Models;
using Tagg.Domain;
using Tagg.Domain.ApiModels;

namespace Tagg.Admin.Controllers
{
    public class TeachersController : Controller
    {
        private IMapper _mapper;
        //private IEmailService _emailService;
        //private IConfiguration _config;
        private TaggApiService _api;

        public TeachersController(TaggApiService api, IMapper mapper)
        {
            _mapper = mapper;
            //_emailService = emailService;
            //_config = config;
            _api = api;
        }

        // GET: Teachers
        public async Task<IActionResult> Index()
        {
            var teachers = await _api.Teachers.GetAll();
            return View(teachers);
        }

        // GET: Teachers/Details/5
        public async Task<IActionResult> Details(string id)
        {
            var teacher = await _api.Teachers.GetById(id);
            return View(teacher);
        }

        // GET: Teachers/Create
        public async Task<IActionResult> Create()
        {
            var model = new TeacherDto();
            var schools = await _api.Schools.GetAll();
            ViewData["schools"] = new SelectList(schools, "Id", "Name");
            return View(model);
        }

        public async Task<IActionResult> Invite(string id)
        {
            var result = await _api.Users.SendInvite(id);
            if (result)
            {
                ViewData["Message"] = $"Invite email sent to {id}.";
                return View();
            }
            ViewData["Message"] = $"Failed to send invite email to {id}.";
            return View();

        }

        public async Task<IActionResult> Delete(string id)
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TeacherDto model)
        {
            if (ModelState.IsValid)
            {
                model.Status = TaggStatus.Pending;
                var response = await _api.Teachers.Create(model, model.SchoolId);
                return RedirectToAction("Details", new { id = response.Email });
                //var result = await createTeacherAsync(teacher, model.SchoolId);
                //if (result.Succeeded)
                //{
                //    // On succeeded, return to index
                //    return RedirectToAction(nameof(Index));
                //}
                //result.Errors.ForEach(e => ModelState.AddModelError("", e));
            }

            // If we get here, there was an error and return the view
            var schools = await _api.Schools.GetAll();
            ViewData["schools"] = new SelectList(schools, "Id", "Name");
            return View(model);
        }

        public IActionResult Upload()
        {
            var model = populateTeacherUploadModel();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upload(TeacherUploadModel model)
        {
            if (model.Upload == null)
            {
                ModelState.AddModelError("Upload", "Please upload a file.");
            }
            if (ModelState.IsValid)
            {
                var uploadResult = await _api.Teachers.Upload(model.SchoolId, model.Upload);
                if (uploadResult)
                {
                    // On succeeded, return to index
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", "An error occurred while uploading teachers. Please check ");
            }

            // If errors, return view to user
            model = await populateTeacherUploadModel(model);
            return View(model);
        }


        public IActionResult Download()
        {
            var pathToSample = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "TaggTeacherUpload.csv");
            return PhysicalFile(pathToSample, "application/octet-stream", "TaggTeacherUpload.csv");

        }

        private async Task<TeacherViewModel> populateTeacherModel(TeacherViewModel model = null)
        {
            if (model == null)
            {
                model = new TeacherViewModel();
            }

            var subjects = await _api.Lookups.GetSubjects();
            var schools = await _api.Schools.GetAll();

            var defaultSchool = !string.IsNullOrWhiteSpace(model.SchoolId) ? model.SchoolId : schools.First().Id.ToString();

            //model.Subjects = subjects.Select(s => new MultiSelectModel { Key = s.Key, Value = s.Value, Selected = true }).ToList();
            model.SchoolList = new SelectList(schools, "Id", "Name", defaultSchool);

            return model;
        }

        private async Task<TeacherUploadModel> populateTeacherUploadModel(TeacherUploadModel model = null)
        {
            if (model == null)
            {
                model = new TeacherUploadModel();
            }

            model.Upload = null;
            var schools = await _api.Schools.GetAll();
            var defaultSchool = !string.IsNullOrWhiteSpace(model.SchoolId) ? model.SchoolId : schools.First().Id.ToString();
            model.SchoolList = new SelectList(schools, "Id", "Name", defaultSchool);
            return model;
        }

        //private async Task<EntityResult> processBulkUpload(TeacherUploadModel model)
        //{
        //    var formFile = model.Upload;
        //    var fileSize = formFile.Length;
        //    var fileName = WebUtility.HtmlEncode(Path.GetFileName(formFile.FileName));
        //    var contentType = formFile.ContentType;
        //    var fileExt = Path.GetExtension(fileName);

        //    if (fileSize > 1048576)
        //    {
        //        return new EntityResult("File size must be less than than 1MB.");
        //    }

        //    if (fileExt != ".csv")
        //    {
        //        return new EntityResult("File must be a CSV (.csv) file.");
        //    }

        //    var errors = new List<string>();
        //    var teachers = new Dictionary<int,Teacher>();

        //    using (var reader = new StreamReader(formFile.OpenReadStream(), 
        //        new UTF8Encoding(encoderShouldEmitUTF8Identifier: false, throwOnInvalidBytes: true),
        //        detectEncodingFromByteOrderMarks: true))
        //    {
        //        var csv = new CsvHelper.CsvReader(reader);
        //        csv.Read();
        //        csv.ReadHeader();
        //        int i = 1;
        //        while (csv.Read())
        //        {
        //            string firstName = csv[0];
        //            string lastName = csv[1];
        //            string email = csv[2];
        //            string phoneNumber = csv[3];
        //            var namePattern = @"([^\w\s]|\d)";      //Any non-word chars and numbers (except space)
        //            var emailPattern = @"[^a-zA-Z0-9@.]";   //Anything that is not a letter, number, @ or period
        //            var phonePattern = @"\D";               //Any non-digit char

        //            var teacherModel = new TeacherViewModel
        //            {
        //                FirstName = Regex.Replace(firstName, namePattern, string.Empty),
        //                LastName = Regex.Replace(lastName, namePattern, string.Empty),    
        //                Email = Regex.Replace(email, emailPattern , string.Empty),
        //                PhoneNumber = Regex.Replace(phoneNumber, phonePattern, string.Empty),
        //                SchoolId = model.SchoolId
        //            };
        //            teachers.Add(i, _mapper.Map<TeacherViewModel, Teacher>(teacherModel));
        //            i++;
        //        }
        //    }
            
        //    foreach (var item in teachers)
        //    {
        //        var creationResult = _api.Teachers.Create(_mapper.Map<TeacherDto>(item.Value), model.SchoolId);
        //        //if (!creationResult.Succeeded)
        //        //{
        //        //    errors.Add($"Error in row {item.Key}: {creationResult.Errors.First()}");
        //        //}
        //    }

        //    var result = new EntityResult();
        //    if (errors.Count > 0)
        //    {
        //        errors.ForEach(e => result.AddError(e));
        //        result.AddError("Teachers have been created for all other rows. Please fix the errors and submit the file again with only the rows listed above.");
        //    }
        //    return result;
        //}

        //// POST: Teachers/Create
        //// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        //// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("Id,UserProfileId,SchoolId")] Teacher teacher)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        _work.Teachers.Upsert(teacher);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }
        //    ViewData["SchoolId"] = new SelectList(_context.Schools, "Id", "Id", teacher.SchoolId);
        //    ViewData["UserProfileId"] = new SelectList(_context.UserProfiles, "Id", "Id", teacher.UserProfileId);
        //    return View(teacher);
        //}

        //// GET: Teachers/Edit/5
        //public async Task<IActionResult> Edit(int? id)
        //{

Tagg/server/Tagg.Admin/Views/Teachers/Create.cshtml
@model Tagg.Domain.ApiModels.TeacherDto

@{
    ViewData["Title"] = "Add Teacher";
}

<div class="dash-container">
    <div class="dash-panel dash-4-center">
        <h3>@ViewData["Title"]</h3>
        <div class="alert alert-info">
            <div>
                <a asp-action="Upload">Click here to bulk upload teachers.</a>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-body">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="form-group text-left">
                        <label class="control-label">School</label>
                        <select asp-for="SchoolId" class="form-control" asp-items="(SelectList)@ViewData["schools"]"></select>
                    </div>
                    <div class="form-group text-left">
                        <label class="control-label">First Name</label>
                        <input asp-for="FirstName" class="form-control" />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                    <div class="form-group text-left">
                        <label class="control-label">Last Name</label>
                        <input asp-for="LastName" class="form-control" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                    <div class="form-group text-left">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="form-group text-left">
                        <label class="control-label">Phone Number</label>
                        <input asp-for="PhoneNumber" class="form-control" />
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                    <div class="form-group text-left">
                        <input type="submit" value="Add Teacher" class="btn btn-success" />
                    </div>
                </form>
            </div>
            <div class="panel-footer">
                <div>
                    <a asp-action="Index">Back to List</a>
                </div>
            </div>
        </div>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Tagg/server/Tagg.Admin/Views/Teachers/Delete.cshtml
@model Tagg.Domain.Teacher

@{
    ViewData["Title"] = "Delete";
}

<h2>Feature coming soon...</h2>

Tagg/server/Tagg.Admin/Views/Teachers/Details.cshtml
@model Tagg.Domain.ApiModels.TeacherDto

@{
    ViewData["Title"] = "Teacher Details";
}

<div class="dash-container">
    <div class="dash-panel dash-4-center">
        <h3>@ViewData["Title"]</h3>
        <div class="panel panel-default">
            <div>
                <dl class="dl-horizontal">
                    <dt>
                        Name
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.FullName)
                    </dd>
                    <dt>
                        Email
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Email)
                    </dd>
                    <dt>
                        Phone Number
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.PhoneNumber)
                    </dd>
                    @if (Model.Address != null)
                    {
                        <dt>
                            Address
                        </dt>
                        <dd>
                            @Model.Address.Street1 @Model.Address.Street2
                        </dd>
                        <dt>
                            City
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Address.City)
                        </dd>
                        <dt>
                            State
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Address.State)
                        </dd>
                        <dt>
                            Postal Code
                        </dt>
                        <dd>
                            @Html.DisplayFor(model => model.Address.PostalCode)
                        </dd>

                    }

                    <dt>
                        Status
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Status)
                    </dd>
                    <dt>
                        Bio
                    </dt>
                    <dd>
                        @Html.DisplayFor(model => model.Bio)
                    </dd>
                </dl>
            </div>
            <div>
                <a asp-action="Index">Back to List</a>
                <a asp-action="Edit" asp-route-id="@Model.Email"> | Edit</a>
                <a asp-controller="Jobs" asp-action="Create" asp-route-id="@Model.Email"> | Create Job</a>

            </div>
        </div>

    </div>
</div>

Tagg/server/Tagg.Admin/Views/Teachers/Edit.cshtml
@model Tagg.Domain.Teacher

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Teacher</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <h2>Under Construction...</h2>
        @*<form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="UserProfileId" class="control-label"></label>
                <select asp-for="UserProfileId" class="form-control" asp-items="ViewBag.UserProfileId"></select>
                <span asp-validation-for="UserProfileId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SchoolId" class="control-label"></label>
                <select asp-for="SchoolId" class="form-control" asp-items="ViewBag.SchoolId"></select>
                <span asp-validation-for="SchoolId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>*@
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Tagg/server/Tagg.Admin/Views/Teachers/Index.cshtml
@model IEnumerable<Tagg.Domain.ApiModels.TeacherDto>

@{
    ViewData["Title"] = "Teachers";
}
<div class="dash-container">
    <div class="dash-panel dash-10">
        <h2>@ViewData["Title"]</h2>
        <div class="pull-right">
            <a asp-action="Create" class="btn btn-success">Create Teacher</a>
        </div>
        <div class="panel panel-default">
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            First Name
                        </th>
                        <th>
                            Last Name
                        </th>
                        <th>
                            Phone
                        </th>
                        <th>
                            Email
                        </th>
                        <th>
                            Status
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.FirstName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.LastName)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.PhoneNumber)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Email)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Status)
                            </td>

                            <td>
                                <a asp-action="Details" asp-route-id="@item.Email">Details</a>
                                @if (item.Status == Tagg.Domain.TaggStatus.New)
                                {
                                    <a asp-action="Invite" asp-route-id="@item.Email"> | Invite</a>
                                }
                                @if (item.Status == Tagg.Domain.TaggStatus.Pending)
                                {
                                    <a asp-action="Invite" asp-route-id="@item.Email"> | Resend</a>
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Tagg/server/Tagg.Admin/Views/Teachers/Invite.cshtml
<div class="dash-container">
    <div class="dash-panel dash-6-center">
        <h2>Teacher Invite</h2>
        <div class="panel panel-default">
            @ViewData["Message"]
        </div>
    </div>
</div>

Tagg/server/Tagg.Admin/Views/Teachers/Upload.cshtml
@model TeacherUploadModel

@{
    ViewData["Title"] = "Upload Teachers";
}

<div class="dash-container">
    <div class="dash-panel dash-4-center">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>@ViewData["Title"]</h3>
            </div>
            <div class="panel-body">
                <div class="alert alert-info">
                    <h3>Instructions</h3>
                    <ul>
                        <li>Download <a asp-action="Download">this sample file</a>.</li>
                        <li>Add teachers with only the information provided. Note - do not modify the file in any other way.</li>
                        <li>Upload the file, then click the Upload Teachers button.</li>
                    </ul>
                </div>
                <form asp-action="Upload" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group text-left">
                        <label asp-for="SchoolId" class="control-label"></label>
                        <select asp-for="SchoolId" class="form-control" asp-items="@Model.SchoolList"></select>
                    </div>
                    <div class="form-group text-left">
                        <label asp-for="Upload" class="control-label"></label>
                        <input asp-for="Upload" type="file" class="form-control" style="height:auto;" />
                        <span asp-validation-for="Upload" class="text-danger"></span>
                    </div>
                    
                    <div class="form-group text-left">
                        <input type="submit" value="Upload Teachers" class="btn btn-success" />
                    </div>
                </form>
            </div>
            <div class="panel-footer">
                <div>
                    <a asp-action="Index">Back to List</a>
                </div>
            </div>
        </div>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}